use serde::Serialize;
use serde_json::Value;
use std::sync::Arc;
use tokio::sync::broadcast;

use super::result::AgentStatus;

/// Real-time events emitted during agent execution for UI consumption.
#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum AgentEvent {
    /// Agent run has started.
    AgentStarted { task: String, timestamp_ms: u64 },
    /// A new iteration of the agent loop began.
    IterationStarted { iteration: u32 },
    /// The model produced a complete thinking/reasoning block.
    ThinkingComplete { thinking: String },
    /// Text content generated by the model.
    TextDelta { text: String },
    /// A tool execution is about to begin.
    ToolUseStart {
        id: String,
        name: String,
        input: Value,
    },
    /// A tool execution completed.
    ToolUseResult {
        id: String,
        name: String,
        output: Value,
        duration_ms: u64,
        is_error: bool,
    },
    /// The agent run completed.
    AgentCompleted {
        status: AgentStatus,
        result: Option<String>,
        total_duration_ms: u64,
    },
    /// The agent encountered an error.
    AgentError { error: String },
}

impl AgentEvent {
    /// Returns the SSE event type string for this event.
    pub fn event_type(&self) -> &'static str {
        match self {
            AgentEvent::AgentStarted { .. } => "agent_started",
            AgentEvent::IterationStarted { .. } => "iteration_started",
            AgentEvent::ThinkingComplete { .. } => "thinking_complete",
            AgentEvent::TextDelta { .. } => "text_delta",
            AgentEvent::ToolUseStart { .. } => "tool_use_start",
            AgentEvent::ToolUseResult { .. } => "tool_use_result",
            AgentEvent::AgentCompleted { .. } => "agent_completed",
            AgentEvent::AgentError { .. } => "agent_error",
        }
    }
}

/// Broadcast-based event bus for distributing agent events to subscribers.
pub struct EventBus {
    sender: broadcast::Sender<AgentEvent>,
}

impl EventBus {
    /// Create a new EventBus with the given channel capacity.
    pub fn new(capacity: usize) -> Self {
        let (sender, _) = broadcast::channel(capacity);
        Self { sender }
    }

    /// Send an event to all subscribers. Silently ignores when there are no subscribers.
    pub fn send(&self, event: AgentEvent) {
        let _ = self.sender.send(event);
    }

    /// Subscribe to the event stream.
    pub fn subscribe(&self) -> broadcast::Receiver<AgentEvent> {
        self.sender.subscribe()
    }
}

/// Helper to emit an event if an event bus is present.
pub fn emit(event_bus: &Option<Arc<EventBus>>, event: AgentEvent) {
    if let Some(ref bus) = event_bus {
        bus.send(event);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_agent_started_serialization() {
        let event = AgentEvent::AgentStarted {
            task: "navigate to google.com".to_string(),
            timestamp_ms: 1710288000000,
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "agent_started");
        assert_eq!(json["task"], "navigate to google.com");
        assert_eq!(json["timestamp_ms"], 1710288000000u64);
    }

    #[test]
    fn test_iteration_started_serialization() {
        let event = AgentEvent::IterationStarted { iteration: 3 };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "iteration_started");
        assert_eq!(json["iteration"], 3);
    }

    #[test]
    fn test_thinking_complete_serialization() {
        let event = AgentEvent::ThinkingComplete {
            thinking: "I need to click the button".to_string(),
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "thinking_complete");
        assert_eq!(json["thinking"], "I need to click the button");
    }

    #[test]
    fn test_text_delta_serialization() {
        let event = AgentEvent::TextDelta {
            text: "Hello world".to_string(),
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "text_delta");
        assert_eq!(json["text"], "Hello world");
    }

    #[test]
    fn test_tool_use_start_serialization() {
        let event = AgentEvent::ToolUseStart {
            id: "toolu_abc".to_string(),
            name: "navigate".to_string(),
            input: json!({"url": "https://google.com"}),
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "tool_use_start");
        assert_eq!(json["id"], "toolu_abc");
        assert_eq!(json["name"], "navigate");
        assert_eq!(json["input"]["url"], "https://google.com");
    }

    #[test]
    fn test_tool_use_result_serialization() {
        let event = AgentEvent::ToolUseResult {
            id: "toolu_abc".to_string(),
            name: "navigate".to_string(),
            output: json!({"success": true}),
            duration_ms: 1200,
            is_error: false,
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "tool_use_result");
        assert_eq!(json["id"], "toolu_abc");
        assert_eq!(json["name"], "navigate");
        assert_eq!(json["output"]["success"], true);
        assert_eq!(json["duration_ms"], 1200);
        assert_eq!(json["is_error"], false);
    }

    #[test]
    fn test_tool_use_result_with_error_serialization() {
        let event = AgentEvent::ToolUseResult {
            id: "toolu_xyz".to_string(),
            name: "click".to_string(),
            output: json!("element not found"),
            duration_ms: 500,
            is_error: true,
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "tool_use_result");
        assert_eq!(json["is_error"], true);
    }

    #[test]
    fn test_agent_completed_serialization() {
        let event = AgentEvent::AgentCompleted {
            status: AgentStatus::Success,
            result: Some("Task done".to_string()),
            total_duration_ms: 5000,
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "agent_completed");
        assert_eq!(json["status"], "success");
        assert_eq!(json["result"], "Task done");
        assert_eq!(json["total_duration_ms"], 5000);
    }

    #[test]
    fn test_agent_completed_without_result() {
        let event = AgentEvent::AgentCompleted {
            status: AgentStatus::Timeout,
            result: None,
            total_duration_ms: 30000,
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "agent_completed");
        assert_eq!(json["status"], "timeout");
        assert!(json["result"].is_null());
    }

    #[test]
    fn test_agent_error_serialization() {
        let event = AgentEvent::AgentError {
            error: "connection failed".to_string(),
        };
        let json = serde_json::to_value(&event).unwrap();
        assert_eq!(json["type"], "agent_error");
        assert_eq!(json["error"], "connection failed");
    }

    #[test]
    fn test_event_type_returns_correct_strings() {
        assert_eq!(
            AgentEvent::AgentStarted {
                task: String::new(),
                timestamp_ms: 0
            }
            .event_type(),
            "agent_started"
        );
        assert_eq!(
            AgentEvent::IterationStarted { iteration: 0 }.event_type(),
            "iteration_started"
        );
        assert_eq!(
            AgentEvent::ThinkingComplete {
                thinking: String::new()
            }
            .event_type(),
            "thinking_complete"
        );
        assert_eq!(
            AgentEvent::TextDelta {
                text: String::new()
            }
            .event_type(),
            "text_delta"
        );
        assert_eq!(
            AgentEvent::ToolUseStart {
                id: String::new(),
                name: String::new(),
                input: json!(null)
            }
            .event_type(),
            "tool_use_start"
        );
        assert_eq!(
            AgentEvent::ToolUseResult {
                id: String::new(),
                name: String::new(),
                output: json!(null),
                duration_ms: 0,
                is_error: false
            }
            .event_type(),
            "tool_use_result"
        );
        assert_eq!(
            AgentEvent::AgentCompleted {
                status: AgentStatus::Success,
                result: None,
                total_duration_ms: 0
            }
            .event_type(),
            "agent_completed"
        );
        assert_eq!(
            AgentEvent::AgentError {
                error: String::new()
            }
            .event_type(),
            "agent_error"
        );
    }

    #[test]
    fn test_event_bus_send_without_subscribers_does_not_panic() {
        let bus = EventBus::new(16);
        bus.send(AgentEvent::AgentStarted {
            task: "test".to_string(),
            timestamp_ms: 0,
        });
    }

    #[tokio::test]
    async fn test_event_bus_subscribe_receives_events() {
        let bus = EventBus::new(16);
        let mut rx = bus.subscribe();

        bus.send(AgentEvent::IterationStarted { iteration: 1 });

        let received = rx.recv().await.unwrap();
        let json = serde_json::to_value(&received).unwrap();
        assert_eq!(json["type"], "iteration_started");
        assert_eq!(json["iteration"], 1);
    }

    #[tokio::test]
    async fn test_event_bus_multiple_subscribers() {
        let bus = EventBus::new(16);
        let mut rx1 = bus.subscribe();
        let mut rx2 = bus.subscribe();

        bus.send(AgentEvent::TextDelta {
            text: "hello".to_string(),
        });

        let ev1 = rx1.recv().await.unwrap();
        let ev2 = rx2.recv().await.unwrap();
        assert_eq!(
            serde_json::to_value(&ev1).unwrap()["text"],
            "hello"
        );
        assert_eq!(
            serde_json::to_value(&ev2).unwrap()["text"],
            "hello"
        );
    }

    #[test]
    fn test_emit_helper_with_none_does_not_panic() {
        emit(&None, AgentEvent::AgentStarted {
            task: "test".to_string(),
            timestamp_ms: 0,
        });
    }

    #[tokio::test]
    async fn test_emit_helper_with_some_sends_event() {
        let bus = Arc::new(EventBus::new(16));
        let mut rx = bus.subscribe();
        let bus_opt = Some(bus);

        emit(&bus_opt, AgentEvent::IterationStarted { iteration: 5 });

        let received = rx.recv().await.unwrap();
        let json = serde_json::to_value(&received).unwrap();
        assert_eq!(json["iteration"], 5);
    }
}
